use_frameworks!

target 'HQMapComponent_Example' do
  pod 'HQMapComponent', :path => '../'

  target 'HQMapComponent_Tests' do
    inherit! :search_paths

    
  end
  pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
end
